# Generated by Django 5.1.6 on 2025-09-18 11:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_education_userprofile_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_location', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoundingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_type', models.TextField(blank=True, null=True)),
                ('industry_type', models.TextField(blank=True, null=True)),
                ('team_size', models.CharField(max_length=50)),
                ('year_established', models.PositiveIntegerField()),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_vision', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.PositiveIntegerField()),
                ('max', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sociallink',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('banner_logo', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('about_us', models.TextField()),
                ('contact_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='users.contactinfo')),
                ('founding_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='users.foundinginfo')),
                ('socials', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='users.sociallinks')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('PART-TIME', 'Part-Time'), ('FULL-TIME', 'Full-Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship')], max_length=20)),
                ('level', models.CharField(blank=True, choices=[('JUNIOR', 'Junior'), ('MID', 'Mid'), ('SENIOR', 'Senior'), ('LEAD', 'Lead')], max_length=20, null=True)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(default=list)),
                ('desirable', models.JSONField(default=list)),
                ('benefits', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_expired', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='users.company')),
                ('salary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.salary')),
            ],
        ),
    ]
