# Generated by Django 5.1.6 on 2025-09-23 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contactinfo_foundinginfo_salary_sociallinks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='users.contactinfo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='founding_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founding', to='users.foundinginfo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='socials',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='users.sociallinks'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='biography',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biography', to='users.biography'),
        ),
    ]
