# Generated by Django 5.1.6 on 2025-09-23 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_biography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='biography',
        ),
        migrations.DeleteModel(
            name='Biography',
        ),
    ]
