# Generated by Django 5.1.6 on 2025-09-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userprofile_biography_delete_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
