# Generated by Django 5.1.6 on 2025-09-24 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_is_company_userprofile_is_onboarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact_info',
        ),
        migrations.AlterField(
            model_name='company',
            name='founding_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='founding', to='users.foundinginfo'),
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
