# Generated by Django 5.1.6 on 2025-09-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_company_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundinginfo',
            name='team_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foundinginfo',
            name='year_established',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
