# Generated by Django 5.1.6 on 2025-09-24 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_foundinginfo_team_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='users.userprofile'),
        ),
    ]
