# Generated by Django 5.1.6 on 2025-09-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_company_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
