# Generated by Django 5.1.6 on 2025-09-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
    ]
