# Generated by Django 5.1.6 on 2025-10-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_jobapplication'),
        ('users', '0013_alter_company_about_us'),
    ]

    operations = [
    ]
