# Generated by Django 5.1.6 on 2025-10-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_contactinfo_remove_company_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
