# Generated by Django 5.1.6 on 2025-10-02 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_company_onboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='users.contactinfo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='founding_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='founding_info', to='users.foundinginfo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='socials',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='users.sociallinks'),
        ),
    ]
