# Generated by Django 5.1.6 on 2025-10-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_userprofile_company_alter_company_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
